# xtract.ini
# The following setting order program to extract MS1 spectra
# from RAWs in the directory of F:\data\directory\ and also
# the RAW F:\data\raw\data.raw. The results will be holding in
# the directory F:\data\output\. Since it is going to export
# MS1, activation setting will be negelected. All spectra will
# export as centroided. The decial place of m/z ratio and
# intensity will be 7 and 6. The charge range will be 2 to 3.
[required]
extension=MS1|MS2|PFB
input_file_path=D:\data\Astral\DIA-2Th\20230306_OLEP08_200ngHek_180k_500AGC_2p5ms_2Th_15min_jvo_nce25_03.raw
[optional]
output_file_path=D:\data\Astral\DIA-2Th
activation=ALL
centroided=ON
mz=7
intensity=6
charge=2-3
